### ISSUE TITLE
could you please help me how do you convert your .js file to json?

### ISSUE THREAD

**Issue by yarishraman** [nickpedersen/artsey_on_karabiner#1]
Hi Nick - 

I am new to Karabiner and ARTSEY keyboard layout. 
could you please help me to complete your TODO? 
is it comlex ? I did not really understood how you have converted your karabiner.js to karabiner.json.

**Comment by nickpedersen** [comment]
Hi @yarishraman - the `.js` file is a Nodejs script, essentially it compiles all of the rules in a format that Karabiner understands, and then exports them as JSON into the file specified. Apologies for the README lacking detail, truthfully I didn’t think anyone else would end up using this! You need Nodejs installed, and then you can run `node artsey.js` to generate a new JSON file.

If you open up the JavaScript file there are comments that should be helpful to understand how it works. 

I think most of those TODOs are quite straightforward. Mouse keys will be a bit trickier as I don’t know what mouse support in Karabiner looks like.

I don’t actually use this code anymore, it was more of an experiment for me to play around with ARTSEY before building a dedicated board.

**Comment by yarishraman** [comment]
Thank you for the response. I will play around and see whether I can complete it :)
